### ISSUE TITLE
日期处理错误导致key error

### ISSUE THREAD

**Issue by iamwyh2019** [pcrbot/schedule#1]
在```return_schedule```中，```date.today()```转为字符串后month和day均为两位，不足两位的带前导0。然而，在数据源json里，月份固定为两位，天数则不带前导0。这导致查看每月1~9号的日程会出错。
希望加入特判，去除day里的前导0。

附：错误日志
![Screenshot_20200830-002643.jpg](https://user-images.githubusercontent.com/51950361/91641981-53140a80-ea5a-11ea-8448-f1f3530c1f32.jpg)

**Comment by zangxx66** [comment]
我的处理方法是这样  
``` 
t = datetime.datetime.today().date() 
year, month, day = str(t).split("-")
if int(day) < 10:  
    day = day[1] 
```

只取日期部分，然后查看day如果是1-9号就只取字符串的第二位

**Comment by H-K-Y** [comment]
抱歉，我最近生病了，在医院没法改，你们自己改一下吧

**Comment by H-K-Y** [comment]
好了，我修了这个问题了

**Comment by iamwyh2019** [comment]
> 好了，我修了这个问题了

谢谢。祝早日康复。
